### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by volodymyr-kushnir** [michaelsypchenko/HomeTask1#3]
Привіт, @michaelsypchenko. Як на рахунок додати до репозиторію **README.md** з коротким описом проекту?

**Comment by michaelsypchenko** [comment]
Привіт. Вже додав...

**Comment by volodymyr-kushnir** [comment]
Шикарно, закриваю проблему ([**пссс, ще пару лайфхаків тут**](https://github.com/volodymyr-kushnir/agenda))
